# Run by default on lowest supported Python version
image: python:3.9

stages:
  # - style
  # - test
  - deploy

# style
style:
  stage: style
  before_script:
    - apt update && apt install -y --no-install-recommends git
    - pip install pre-commit
  script:
    - pre-commit run --all-files --show-diff-on-failure

# test
test38:
  stage: test
  before_script:
    - pip install -e .
    - pip install pytest
  script:
    - pytest tests

# deploy
deploy:
  stage: deploy
  script:
    - pip install poetry
    - poetry self add "poetry-dynamic-versioning[plugin]"
    - poetry config pypi-token.pypi $PYPI_TOKEN
    - poetry publish --build
  only:
    # Only deploy refs that are a version tag (v*.*.*)
    - /^v\d+\.\d+\.\d+.*$/
  except:
    # only deploy tags
    - branches

winpython-generation:
  stage: deploy
  tags:
    - saas-windows-medium-amd64 
  script: 
    - choco install python --version=3.10 -y -f
    - python -m pip install --upgrade pip
    - python -m pip install poetry
    - git clone http://user_1:$WINPYTHON_TOKEN@gitlab.com/rtc-tools-project/generate_portable_winpython.git
    - cd generate_portable_winpython
    - poetry install
    - Invoke-Expression '@"
      rtc-tools
      rtc-tools-interface
      rtc-tools-diagnostics
      rtc-tools-hydraulic-structures
      rtc-tools-simulation
      "@ | Out-File -FilePath requirements.txt'
    - poetry run generate-portable-winpython --name py310-rtc --installer_url "https://github.com/winpython/winpython/releases/download/6.1.20230527/Winpython64-3.10.11.1dot.exe" --requirements_txt "requirements.txt"